###
POST http://localhost:3000/top-quotes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiaTEyMyIsImlhdCI6MTcwNjIwNjA1Nn0.HdsRPrEvodtw7yiOfd2mttTcxQFVizami1T1Oj-Ilw0
Content-Type: application/json
  
     {
    "author": "Coco Chanel",
    "quote": "The most courageous act is still to think for yourself. Aloud.",
    "explanation": "Coco Chanel celebrates the courage of independent thought and expression, suggesting that true bravery lies in challenging conventional wisdom and voicing ones own beliefs."
  }
###
GET http://localhost:3001/all-quotes?author=Sai%20Baba

###
GET http://localhost:3001/all-quotes?search_q=dreams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiaTEyMyIsImlhdCI6MTcwNjIwNjA1Nn0.HdsRPrEvodtw7yiOfd2mttTcxQFVizami1T1Oj-Ilw0

### 
POST http://localhost:3000/upload-quotes/
Content-Type: application/json
   
    {
    "author": "Maya Angelou",
    "quote": "You may not control all the events that happen to you, but you can decide not to be reduced by them.",
    "explanation": "Maya Angelou speaks to the resilience of the human spirit, suggesting that while we may face adversity, we have the power to rise above it and define our own narrative."
  }

### all quotes get
GET http://localhost:3001/all-quotes/?search=''
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiaTEyMyIsImlhdCI6MTcwNjI0MzQwMH0.8iedOxC7DT9Nj-0uii_QQPCg7sjD5SPwdHhz37H7xF4

### get a particular quote from all quotes
GET http://localhost:3001/all-quotes/11

### register 
POST http://localhost:3001/register/
Content-Type: application/json

  {
      "username":"1234",
      "password":"1234",
      "name":"abinandhan",
      "gender":"Male",
      "location":"Aruppukottai",
      "age":20,
      "occupation":"Software Engineer",
      "mail":"abinandhan123@gmail.com",
      "mobilenumber":453179687126549

  }

### login
POST http://localhost:3001/login/
Content-Type: application/json

  {
      "username":"vima",
      "password":"12345678910"
  }
### top quotes get
GET http://localhost:3001/top-quotes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiaTEyMyIsImlhdCI6MTcwNjI0MzQwMH0.8iedOxC7DT9Nj-0uii_QQPCg7sjD5SPwdHhz37H7xF4

### top quotes delete
DELETE http://localhost:3000/top-quotes/11

###profile 
GET http://localhost:3001/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiaTEyMyIsImlhdCI6MTcwNjI0MzQwMH0.8iedOxC7DT9Nj-0uii_QQPCg7sjD5SPwdHhz37H7xF4

###
GET http://localhost:3001/author-quotes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiaTEyMyIsImlhdCI6MTcwNjI0MzQwMH0.8iedOxC7DT9Nj-0uii_QQPCg7sjD5SPwdHhz37H7xF4

###
POST http://localhost:3001/my-quotes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiaTEyMyIsImlhdCI6MTcwNjI0MzQwMH0.8iedOxC7DT9Nj-0uii_QQPCg7sjD5SPwdHhz37H7xF4
Content-Type: application/json

{
    "userid":"3",
    "quote":"temp",
    "explanation":"dfg"
}

###
GET http://localhost:3001/my-quotes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbWEiLCJpYXQiOjE3MDY0MTA4MDJ9.i3020NdtcsTGe0kQfG8GrkC4LE4LgrbpGdexcNGPnrw

###
DELETE http://localhost:3001/my-quotes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiaTEyMyIsImlhdCI6MTcwNjI0MzQwMH0.8iedOxC7DT9Nj-0uii_QQPCg7sjD5SPwdHhz37H7xF4
Content-Type: application/json

{
    "quoteid":100
}

###
PUT http://localhost:3001/my-quotes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbWEiLCJpYXQiOjE3MDY0MTA4MDJ9.i3020NdtcsTGe0kQfG8GrkC4LE4LgrbpGdexcNGPnrw
Content-Type: application/json

{
    "quoteid":23,
    "quote":"ashwant",
    "explanation":"saravanan"
}

